[tool.poetry]
authors = ["Jason Xia <jasonxh@gmail.com>"]
description = ""
name = "arlo-mqtt"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.7"

Homie3 = "^0.3.0"
arlo = "^1.2.50"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
mypy = "^0.910"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
