name: CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Prepare venv
        run: poetry install --no-interaction

      - name: Run black
        run: poetry run black --check .

      - name: Run isort
        run: poetry run isort --check .

      - name: Run mypy
        run: poetry run mypy .

      - name: Export requirements.txt
        run: poetry export --without-hashes -o requirements.txt

      - name: Build wheel
        run: poetry build --format wheel

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ github.repository }}:latest
